### ISSUE TITLE
Not working on Brave because of insufficient site-access

### ISSUE THREAD

**Issue by AryanVerma1024** [MonsterMannen/reddit-load-images-directly-chrome#1]
This extension is not working on the Brave web browser since reddit changes the images to open on *www.reddit.com/media?=url*.

This might be happening because *maybe* the extension is only requesting access to the following sites when it is installed on Brave:
![image](https://github.com/MonsterMannen/reddit-load-images-directly-chrome/assets/80571430/018352fa-2875-44bd-9b99-28bbeb398d13)

When installed on other browsers it gets the dropdown menu in which we can select the different options of access (e.g. Edge)
![image](https://github.com/MonsterMannen/reddit-load-images-directly-chrome/assets/80571430/4f222d99-2241-4a2f-b253-0dabf019766b)

This might seem like an issue with Brave but other extensions have the proper dropdown selector in Brave (e.g. Redirector):
![image](https://github.com/MonsterMannen/reddit-load-images-directly-chrome/assets/80571430/91984cd0-7daa-438c-9a22-d534f58e2627)

**Comment by AryanVerma1024** [comment]
quick fix that works

change `host_permissions` in manifest to
`["*://*/*"]`

**Comment by ShadyDeth** [comment]
I am having the same issue while using Brave. It seems like the extension is hit or miss whether it wants to work. Most of the time it chooses not to.

Since the extension is already running on reddit images, I just decided to add reddit itself and it seems to have solved the issue. I've only tested for about 30 minutes though.

I added `"*://*.reddit.com/*"` to `"host_permissions"` and added a new rule with `"urlFilter" : "|*://*.reddit.com/*",`

**Comment by MonsterMannen** [comment]
@ShadyDeth care to make a PR with the fix?

**Comment by ShadyDeth** [comment]
@MonsterMannen WIll do.

**Comment by MonsterMannen** [comment]
> @MonsterMannen WIll do.

You answered quick :D Already submitted the fix to chrome webstore but thanks anyways.
We just have to wait a day or two for the update to go live :)

**Comment by MonsterMannen** [comment]
I made a small mistake, forgot to actually include the rule in the manifest file.. so we have to wait a bit longer since I cant resubmit the update to chrome webstore until the failed version is approved. Sorry :(

**Comment by AryanVerma1024** [comment]
i for some reason went a whole different path and created a new rule to redirect the media pages to i.redd 😅
```
[
    {
        "id": 4,
        "priority": 1,
        "action": {
            "type": "redirect",
            "redirect": {
                "regexSubstitution" : "https://i.redd.it/\\2.\\3"
            }
        },
        "condition": {
            "regexFilter": ".*(t%2F)([a-zA-Z0-9]+).([a-zA-Z]+).*",
            "resourceTypes": ["main_frame"]
        }
    }
]
```
![image](https://github.com/MonsterMannen/reddit-load-images-directly-chrome/assets/80571430/aea3da0c-d26b-4bd6-8e77-ab450cfa3a8a)
