### ISSUE TITLE
Not working reliably in Brave

### ISSUE THREAD

**Issue by FnordMan** [MonsterMannen/reddit-load-images-directly-chrome#2]
On install it'll work fine for however long you keep the browser open.

After you close and re-open it later it stops working. Sometimes disabling and re-enabling it works other times one has to remove and reinstall the extension.

**Comment by MonsterMannen** [comment]
@AryanVerma1024
@ShadyDeth

Brave bois (or girls), you still using the extension?

I'm not using brave myself anymore, can't really help :(

**Comment by AryanVerma1024** [comment]
@MonsterMannen I moved on to Fox but on Brave I just enabled both my fork and your extension and it worked fine.

**Comment by FnordMan** [comment]
> @MonsterMannen I moved on to Fox but on Brave I just enabled both my fork and your extension and it worked fine.
> 
> Also, use these two in Redirector extension 
Do you have any more details on those? (like the edit button details) There appears to be something missing in the picture

**Comment by AryanVerma1024** [comment]
@FnordMan 

![image](https://github.com/MonsterMannen/reddit-load-images-directly-chrome/assets/80571430/ca4c5a52-3d73-4665-a7cc-70be5c86433d)
![image](https://github.com/MonsterMannen/reddit-load-images-directly-chrome/assets/80571430/b5b6361e-9af6-44c9-a69a-ec21e3408bde)

**Comment by FnordMan** [comment]
Weird, put everything in like that and it doesn't work

Did manage to get it working with this though: https://www.reddit.com/r/bugs/comments/137s88l/direct_links_to_reddithosted_images_redirect_to/jvgn7vw/

**Comment by Coffeeling** [comment]
> @AryanVerma1024 @ShadyDeth
> 
> Brave bois (or girls), you still using the extension?
> 
> I'm not using brave myself anymore, can't really help :(

I am, and can confirm it's stopped working for some reason. Did a wonderful job while it functioned.
