### ISSUE TITLE
Badge rating is fake

### ISSUE THREAD

**Issue by darkly77** [MonsterMannen/reddit-load-images-directly-chrome#7]
The [README's](https://github.com/MonsterMannen/reddit-load-images-directly-chrome/blob/master/README.md) real badge rating was replaced with a fake one in this commit: https://github.com/MonsterMannen/reddit-load-images-directly-chrome/commit/43cbf35971cc6401d0baa5c81ecdfbde16d1ebd5

This was done to cover up the score decreasing, which was due to people giving bad reviews because the extension has been hijacked. The score isn't available at all now anyway, as the extension was removed from the Chrome store, presumably due to this abuse of trust and policy.

**Old (real) badges:**
![](https://img.shields.io/chrome-web-store/rating/fpimmmjbglpnlpbfikgekaaeinminolo) ![](https://img.shields.io/chrome-web-store/rating-count/fpimmmjbglpnlpbfikgekaaeinminolo) ![](https://img.shields.io/chrome-web-store/users/fpimmmjbglpnlpbfikgekaaeinminolo)

**New (fake) badge:**
![](https://i.imgur.com/vAmDmOh.png)

_And yeah I know this issue is gonna get deleted, reporting it anyway_ 🤷‍♂️

**Comment by MonsterMannen** [comment]
Added a note to the readme 🤷‍♂️

lol the extension actually got removed
